version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@spectrum-css/icon"
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
  - dependency-name: "@adobe/spectrum-css-workflow-icons"
    versions:
    - 1.2.0
  - dependency-name: svg-to-svelte
    versions:
    - 2.2.0
